services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-pgcrypto.sql:/docker-entrypoint-initdb.d/init-pgcrypto.sql:ro

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DB_URL: postgres://user:password@db:5432/users_db?sslmode=disable
      JWT_SECRET: supersecretkey
    ports:
      - "50051:50051"
    restart: unless-stopped
    command: ["./wait-for-it.sh", "db:5432", "--", "./user-service"]

volumes:
  pgdata:
