services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts/init-multi-db.sh:/docker-entrypoint-initdb.d/init-multi-db.sh

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    depends_on:
      - db
      - migrate-user
    environment:
      DB_URL: host=db user=user password=password dbname=users_db port=5432 sslmode=disable
      JWT_SECRET: supersecretkey
    ports:
      - "50051:50051"
    restart: unless-stopped
    entrypoint: ["/wait-for-it.sh", "db:5432", "--", "./user-service"]
    volumes:
      - ./scripts/wait-for-it.sh:/wait-for-it.sh

  migrate-user:
    image: migrate/migrate
    entrypoint: ["/wait-for-it.sh", "db:5432", "--", "migrate"]
    command: [
      "-path=/migrations",
      "-database=postgres://user:password@db:5432/users_db?sslmode=disable",
      "up"
    ]
    volumes:
      - ./user-service/migrations:/migrations
      - ./scripts/wait-for-it.sh:/wait-for-it.sh
    depends_on:
      - db
    networks:
      - default

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    depends_on:
      - user-service
    ports:
      - "8080:8080"
    environment:
      GATEWAY_PORT: 8080
    restart: unless-stopped
    command: ["./api-gateway"]

  gateway_test:
    image: golang:1.23
    working_dir: /app
    volumes:
      - ./api-gateway:/app
    command: ["go", "test", "./test/..."]
    restart: "no"
    depends_on:
      - api-gateway
      - user-service

  task-service:
    build:
      context: ./task-service
      dockerfile: Dockerfile
    depends_on:
      - db
      - migrate-task
    environment:
      DB_URL: host=db user=user password=password dbname=tasks_db port=5432 sslmode=disable
      JWT_SECRET: supersecretkey
      TASK_SERVICE_PORT: 50052
    ports:
      - "50052:50052"
    restart: unless-stopped
    entrypoint: ["/wait-for-it.sh", "db:5432", "--", "./task-service"]
    volumes:
      - ./scripts/wait-for-it.sh:/wait-for-it.sh

  migrate-task:
    image: migrate/migrate
    entrypoint: ["/wait-for-it.sh", "db:5432", "--", "migrate"]
    command: [
      "-path=/migrations",
      "-database=postgres://user:password@db:5432/tasks_db?sslmode=disable",
      "up"
    ]
    volumes:
      - ./task-service/migrations:/migrations
      - ./scripts/wait-for-it.sh:/wait-for-it.sh
    depends_on:
      - db
    networks:
      - default

volumes:
  pgdata:
