name: CI/CD

on: [push, pull_request]

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      - name: Build all services
        run: |
          docker-compose build
      - name: Run user-service migrations
        run: |
          docker-compose run --rm migrate-user
      - name: Run task-service migrations
        run: |
          docker-compose run --rm migrate-task
      - name: Run user-service tests
        run: |
          docker-compose run --rm user_test
      - name: Run api-gateway tests
        run: |
          docker-compose run --rm gateway_test
      - name: Run task-service tests
        run: |
          docker-compose run --rm task-service go test ./test/...