name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and test with docker-compose
        run: |
          docker-compose build
          docker-compose run --rm migrate
          docker-compose run --rm test
